### ISSUE TITLE
How to handle language plugin not finding definition?

### ISSUE THREAD

**Issue by shabbyrobe** [idbrii/vim-tagimposter#1]
Hello! Thanks so much for this plugin, I found it while searching for a workable solution to  https://github.com/racer-rust/vim-racer/issues/89

I ran into an issue where racer does not find a definition for a Rust function and the buffer does not change, but the tag stack still shows the failed lookup and I have to pop it off.

Here's an asciicast (hopefully) showing the issue where I attempt to go to definition on the `read_to_end` function: https://asciinema.org/a/5bmPoiEoLpcwWKs9jdf45Mdl7

Is there a way I can avoid this happening with this plugin?

**Comment by shabbyrobe** [comment]
Vim has implemented `gettagstack` and `settagstack`, maybe this plugin is no longer needed: https://github.com/vim/vim/pull/3604

**Comment by idbrii** [comment]
You'd have to check that the jump was successful (see if getcurpos() has changed?) and if not, pop it off. Since this plugin doesn't handle jumping, it can't handle that part for you.

You're right that anything that can use gettagstack is better. I should add an example to the readme. Something like https://github.com/racer-rust/vim-racer/commit/6fe615ecedce06df9ec2624dd8f2ae0b3b69c4f5
